### ISSUE TITLE
Opacity does not work consistently

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/mesh-viewer#12]
Steps to reproduce:
1. I was looking at this example model https://dev.facebase.org/mesh-viewer/view.html?model=https://dev.facebase.org/data/mesh/19dpf/19model.json
2. reduce the opacity of some object like the `Epiphyseal Bar`
3. rotate the model around

What you can observe is that you can see through the less opaque object to other objects in some cases but not all. Its like for some objects the `Epiphyseal Bar` is still completely opaque and in other cases it exhibits the expected transparency.

**Comment by robes** [comment]
We should get back to this issue. Here's another set of steps to reproduce:

1. open https://cirm-dev.isrd.isi.edu/~mei/mesh-viewer/view.html?model=https://cirm-dev.isrd.isi.edu/data/mesh/3mesh/3model.json
2. click "Meshes"
3. expand "Mandible"
4. drag opacity slider to nearly complete transparent
5. rotate the model around but you can never see through the mandible to the other two mesh objects in the scene

**Comment by meihuisu** [comment]
I can see through it, I am using firefox.


what are you using?

________________________________

**Comment by robes** [comment]
You’re right. It also works for me with Firefox and Safari.

The problem I described only applies to Chrome.

We should test on Windows too.

**Comment by meihuisu** [comment]
maybe related to this,

https://discourse.wicg.io/t/chrome-53-breaks-css3d-with-opacity-flattening/1694

[http://discourse.wicg.io/uploads/default/original/1X/7f3b669379175496361014a9ff1f73d7cba5cc0a.png]<https://discourse.wicg.io/t/chrome-53-breaks-css3d-with-opacity-flattening/1694>

Chrome 53 breaks CSS3D with opacity flattening - WICG<https://discourse.wicg.io/t/chrome-53-breaks-css3d-with-opacity-flattening/1694>
discourse.wicg.io
Chrome 53 implemented the new css-transforms spec, which mandates that object be flattened when opacity is applied to them. Details: https://bugs.chromium.org/p/chromium/issues/detail?id=646993 This doesn't make sen…



________________________________

**Comment by NickolausDS** [comment]
I found one solution here, which fixes opacity but can cause a little bit of popping if two meshes intersect. #20

**Comment by NickolausDS** [comment]
Pull Request was merged here: https://github.com/informatics-isi-edu/mesh-viewer/pull/20

This issue should be resolved.
