### ISSUE TITLE
Use standard (bootstrap) style sheet for UI elements

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/mesh-viewer#3]

**Comment by robes** [comment]
any luck with using same bootstrap style sheet as the 2D (OSD) viewer?

**Comment by meihuisu** [comment]
demo.html with a row of buttons on the top?

----- Original Message -----

**Comment by robes** [comment]
is demo.html somewhere?

but to answer your question, see the new issue #6 for the overall layout to aim for at this point.

**Comment by robes** [comment]
okay, i see its here https://dev.facebase.org/~mei/mesh-viewer/demo.html

so yes, that's fine with me. let's just stick with it. its more consistent with the 2d viewer in a way.

**Comment by robes** [comment]
so regarding the right hand control... anyway you can put that in a slide out like the "channels" control of the OSD viewer? Have it slide out/in?

**Comment by meihuisu** [comment]
https://dev.facebase.org/~mei/mesh-viewer/demo.html?meshurl=https://dev.facebase.org/data/mesh/19dpf/19dpf.json
----- Original Message -----

**Comment by robes** [comment]
I'd like to keep these issue from getting confusing. This issue was purely about updating the style sheet so that we have the basic style sheet in place. If that is updated please move this issue to the Review pipeline. thanks
