### ISSUE TITLE
Fetch model attributes in parts rather than a whole model spec

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/mesh-viewer#37]
Currently the mesh viewer fetches the model_json object from a single GET request to ERMrest. This requires ERMrest to have a SQL View defined in its underlying database that will construct the (relatively) complex model_json format. What we'd like to do is to have the mesh-viewer make multiple, simpler GETs to fetch each part of the model specification. I.e., 

1- GET the model record
2- GET the model's mesh records
3- GET the model's landmark records

This would allow us to retire the SQL View from our database, which is not fully supported by ERMrest.

**Comment by carlkesselman** [comment]
Not to make trouble, but it would be nice if we could do this in a somewhat generic manner.  I wonder if there is a general calls of apps that are configured by providing a series of gets and then call the app.  Isn’t this in some way related to how the exporter works?  It might be nice to have an exporter like spec that creates a named series of gets and then calls the app.  We could then reuse this of other types of plots.

Carl


On Oct 30, 2018, at 11:42 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently the mesh viewer fetches the model_json object from a single GET request to ERMrest. This requires ERMrest to have a SQL View defined in its underlying database that will construct the (relatively) complex model_json format. What we'd like to do is to have the mesh-viewer make multiple, simpler GETs to fetch each part of the model specification. I.e.,

1- GET the model record
2- GET the model's mesh records
3- GET the model's landmark records

This would allow us to retire the SQL View from our database, which is not fully supported by ERMrest.

**Comment by NickolausDS** [comment]
@robes Can you provide an example of the HTTP requests mesh-viewer would need to make? The last Model had JSON like the model below (slimmed down for example). Are each of the `id`s enough information in the landmarks and meshes to make calls back to ERM?
```
[
    {
        "volume": null, 
        "description": null, 
        "RMT": "2018-05-08T15:58:41.403327-07:00", 
        "RCT": "2018-05-07T15:10:36.631135-07:00", 
        "label": "E18.5 wildtype mouse - hard tissue", 
        "RMB": "https://auth.globus.org/aea1663e-d274-11e5-b9ec-e3afd736021f", 
        "bgcolor": [0, 0, 0],
        "RID": "3VAJ", 
        "bboxcolor": [1, 1, 0], 
        "id": "33", 
        "RCB": "https://auth.globus.org/aea1663e-d274-11e5-b9ec-e3afd736021f", 
        "mesh": [
            {
                "opacity": 1, 
                "description": null, 
                "url": "/hatrac/facebase/previews/fb2/63045/63055/frontalbone.obj.gz", 
                "label": null, 
                "color": [0, 0.6, 0.8], 
                "link": {
                    "url": "/chaise/record/#1/vocab:anatomy/RID=1-41XA", 
                    "label": "Frontal bone"
                }, 
                "id": "3V6T"
            }
        ], 
        "landmark": [
            {
                "group": "3V72", 
                "description": "Mandible 1", 
                "point": [10,3, 3], 
                "color": [1, 0, 0], 
                "label": "Mandible 1", 
                "link": null, 
                "radius": 0.1, 
                "id": "1-3X60"
            }
        ]
    }
]
```

**Comment by robes** [comment]
@NickolausDS yes I'll definitely help to define what those GET urls would be. I'm first trying to see whether we could actually get all of the data in a single (but more complex) query to ERMrest without using the SQL View. If that's possible then instead of having you make more than 1 GET, you'll still make just 1 GET but the response body will be different. It will contain all the same information but not be structured the same way. For example, here's an URL that fetches the model and mesh details.

https://www.facebase.org/ermrest/catalog/1/attributegroup/model:=viz:model/RID=8PA/MMD:=viz:model_mesh_data/MD:=isa:mesh_data/$model/model:RID;model:*,mesh_model_data:=array(MMD:*),mesh_data:=array(MD:*)

As you can see, much of the same info is there but presented differently than what you are getting now.

I can definitely extend this to get the landmarks, and I think I can extend it to get the vocabulary labels you would need.

**Comment by robes** [comment]
@NickolausDS After some discussion/advice from over here, I'm back to thinking that the 3 GETs will be the better way to do this.

So we'd want to update the query params to pass you these 3 urls. 1 to fetch the model (without nested meshes and landmarks) slightly changed, 2 to get the meshes, and 3 to get the landmarks.

Also we should make one trivial fix to the URL format. Right now we have wrongly used the URL queryopt `?...` and instead should change this to a proper fragment identifier syntax `#...` Like

```.../mesh-viewer#model=model_url&meshes=mesh_url&landmarks=landmark_url```

Its actually not just an aesthetic issue, but we will need to have very long URLs for these 3 GET URLs to fit in the params and some servers will not handle long URLs but clients will.

Examples of each:
- model url
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=8PA/*
- mesh url
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=8PA/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/anatomy:=left(mesh:anatomy)/$mesh/RID,url,filename,label,description,color_r:=model_mesh:color_r,color_g:=model_mesh:color_g,color_b:=model_mesh:color_b,opacity:=model_mesh:opacity,anatomy:=anatomy:name
- landmark url
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=8PA/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/L:=viz:landmark/anatomy:=left(anatomy)/$L/RID,mesh,label,description,point_x,point_y,point_z,radius,color_r,color_g,color_b,anatomy:=anatomy:name

Check these out. The output of them is not set in stone but you can get a good idea of what the change entails. Some minor issues I think. Like the "color" would be sent to you as 3 separate properties color_r, color_g, and color_b just because that's how we have had to normalize it in the database. And they are also in `0..255` space so there could be some conversion required? But again, minor stuff.

**Comment by NickolausDS** [comment]
I took a look at how mesh-viewer loads content and this should very much be doable, though I think each request will need to be made before the mesh-viewer initializes, so all of the data can be sent to X before the call is made to X to initialize. There is room in the mesh-viewer for validating fields before they're sent to the X engine, so we could handle `color_r`, `color_g`, `color_b` separately before X sees them.

**Comment by NickolausDS** [comment]
Hi @robes, the initial changes are out. Currently, the mesh viewer can handle the mesh fragment above with the following path:

* `.../mesh-viewer#meshes=https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=8PA/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/anatomy:=left(mesh:anatomy)/$mesh/RID,url,filename,label,description,color_r:=model_mesh:color_r,color_g:=model_mesh:color_g,color_b:=model_mesh:color_b,opacity:=model_mesh:opacity,anatomy:=anatomy:name`

Do you have a link containing some landmarks? The one above returns an empty list for me, I'd like to make sure the mesh-viewer can handle the new attribute names correctly.

**Comment by robes** [comment]
@NickolausDS I found a better model example. This one has landmarks. Let me repeat each part of the model, meshes, landmarks to be fetched.

* model (note the `*` on the end of this URL)
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/*
* meshes
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/anatomy:=left(mesh:anatomy)/$mesh/RID,url,filename,label,description,color_r:=model_mesh:color_r,color_g:=model_mesh:color_g,color_b:=model_mesh:color_b,opacity:=model_mesh:opacity,anatomy:=anatomy:name
* landmarks
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/L:=viz:landmark/anatomy:=left(anatomy)/$L/RID,mesh,label,description,point_x,point_y,point_z,radius,color_r,color_g,color_b,anatomy:=anatomy:name

For comparison, the above would be the individual parts for the model displayed here:

https://dev.facebase.org/mesh-viewer/view.html?model=/ermrest/catalog/1/entity/viz:model_json/RID=1-43KT

Something we would be missing with this approach will be the links back to the anatomy pages. In the above, you will see that we are projecting `...anatomy:=anatomy:name` meaning we are only projecting out the anatomy's human readable name. One thought here is that we also project out `...anatomy_id:=anatomy:id` and then pass one more parameter to tell the mesh viewer how to use that `anatomy_id` to for a link. Like we could add one more param `...&anatomy_url=` where the value is a url-quoted URL like `https://www.facebase.org/ermrest/catalog/1/entity/vocab:anatomy/id=` and then the mesh viewer needs to take that string, url-unquote it, and then append the `anatomy_id` to it, in order to form the link. Unless you have a better suggestion. That's the first idea that crosses my mind here.

**Comment by NickolausDS** [comment]
Thanks! The new model/mesh/landmark info was very helpful, I pushed the extra fixes for landmarks to parse and display. The result looks like:

<img width="1237" alt="screen shot 2018-11-27 at 9 03 07 am" src="https://user-images.githubusercontent.com/865553/49098306-75dd1380-f223-11e8-9cc7-f58ff394b666.png">

For reference, the URL I tested with is: 

  
  http://localhost:8000/view.html#model=https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/*&meshes=https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/anatomy:=left(mesh:anatomy)/$mesh/RID,url,filename,label,description,color_r:=model_mesh:color_r,color_g:=model_mesh:color_g,color_b:=model_mesh:color_b,opacity:=model_mesh:opacity,anatomy:=anatomy:name&landmarks=https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/L:=viz:landmark/anatomy:=left(anatomy)/$L/RID,mesh,label,description,point_x,point_y,point_z,radius,color_r,color_g,color_b,anatomy:=anatomy:name


I'm now noticing the bug you mentioned before about too many entries making the list scroll past the page. 

Let me make sure I understand the purpose of having `anatomy_id`. Is the purpose to avoid duplicating the URL many times for each mesh/landmark so we don't end up with massively long URLs?  Implementation wise, making another GET shouldn't be a problem, or building the URLs after the fact for landmarks and meshes. I do like the idea of encoding all four query parameters on the main URL.

**Comment by NickolausDS** [comment]
That's pretty straight forward. I'm still a bit unfamiliar with how ERM REST works, so an example of a mesh or landmark URL fragment containing the right attribute to generate the `anatomy_id` would be very helpful. The code required to build the URLs should be straightforward and simple. 

I'll also look at fixing the scrolling bug too.

**Comment by robes** [comment]
> I now see anatomy_id popping up. Given a base URL, I could construct the full URLs and make them links on the mesh side.

Exactly.

> Would ...&anatomy_url= change across any meshes?

No, it would always be the same.

**Comment by robes** [comment]
One other comment here. I'm not sure that I've been passing properly url quoted values to the mesh-viewer. If not, I should change that in the real deployments. That is, each fragment id argument value, for example `meshes=VALUE`, should be expected to be url quoted and the mesh viewer have to url unquote them before use.

**Comment by NickolausDS** [comment]
Yes, I completely agree. I'll change the mesh-viewer so it expects them to be quoted. 

Can you post a full example URL with the `anatomy_url`?

**Comment by robes** [comment]
This should be a complete example.

Overall url will look like this but I'm going to break out each `<...>` part separately for readability.

`.../mesh-viewer#model=<model_url>&meshes=<mesh_url>&landmarks=<landmark_url>&anatomy_url=<anatomy_url_fragment>`

Each part listed below should be urlquoted and then plugged into the above format by the caller to the mesh viewer.

* `<model_url>` (note the `*` on the end of this URL)
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/*
* `<mesh_url>`
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/anatomy:=left(mesh:anatomy)/$mesh/RID,url,filename,label,description,color_r:=model_mesh:color_r,color_g:=model_mesh:color_g,color_b:=model_mesh:color_b,opacity:=model_mesh:opacity,anatomy:=anatomy:name
* `<landmark_url>`
  - https://dev.facebase.org/ermrest/catalog/1/attribute/viz:model/RID=1-43KT/model_mesh:=viz:model_mesh_data/mesh:=mesh_data/L:=viz:landmark/anatomy:=left(anatomy)/$L/RID,mesh,label,description,point_x,point_y,point_z,radius,color_r,color_g,color_b,anatomy:=anatomy:name
* `<anatomy_url_fragment>`
  - https://dev.facebase.org/ermrest/catalog/1/entity/vocab:anatomy/RID=

**Comment by NickolausDS** [comment]
Ok, I added the changes above. The full link here:
  http://localhost:8000/view.html#model_url=https%3A%2F%2Fdev.facebase.org%2Fermrest%2Fcatalog%2F1%2Fattribute%2Fviz%3Amodel%2FRID%3D1-43KT%2F%2A&meshes_url=https%3A%2F%2Fdev.facebase.org%2Fermrest%2Fcatalog%2F1%2Fattribute%2Fviz%3Amodel%2FRID%3D1-43KT%2Fmodel_mesh%3A%3Dviz%3Amodel_mesh_data%2Fmesh%3A%3Dmesh_data%2Fanatomy%3A%3Dleft%28mesh%3Aanatomy%29%2F%24mesh%2FRID%2Curl%2Cfilename%2Clabel%2Cdescription%2Ccolor_r%3A%3Dmodel_mesh%3Acolor_r%2Ccolor_g%3A%3Dmodel_mesh%3Acolor_g%2Ccolor_b%3A%3Dmodel_mesh%3Acolor_b%2Copacity%3A%3Dmodel_mesh%3Aopacity%2Canatomy%3A%3Danatomy%3Aname%2Canatomy_id%3A%3Danatomy%3ARID&landmarks_url=https%3A%2F%2Fdev.facebase.org%2Fermrest%2Fcatalog%2F1%2Fattribute%2Fviz%3Amodel%2FRID%3D1-43KT%2Fmodel_mesh%3A%3Dviz%3Amodel_mesh_data%2Fmesh%3A%3Dmesh_data%2FL%3A%3Dviz%3Alandmark%2Fanatomy%3A%3Dleft%28anatomy%29%2F%24L%2FRID%2Cmesh%2Clabel%2Cdescription%2Cpoint_x%2Cpoint_y%2Cpoint_z%2Cradius%2Ccolor_r%2Ccolor_g%2Ccolor_b%2Canatomy%3A%3Danatomy%3Aname%2Canatomy_id%3A%3Danatomy%3ARID&anatomy_url_fragment=https%3A%2F%2Fdev.facebase.org%2Fid%2F

Results in the following:

<img width="1280" alt="screen shot 2018-12-06 at 1 50 36 pm" src="https://user-images.githubusercontent.com/865553/49615015-08d32780-f961-11e8-95c5-0d649dcdf25f.png">

Each of the mesh entries are now links, in addition to each of the landmark entries. An example of the maxilla mesh link and the first selected landmark are here:
* maxilla -- https://dev.facebase.org/id/1-43D4
* Anterior point of maxilla -- https://dev.facebase.org/id/1-43D8

This should comprise of all the changes we've discussed so far. One final note is these changes do modify the API defined in the README, should I change that to show these four params along with an example of the output?

**Comment by robes** [comment]
Yeah, please do update the README.

Did you drop support for the existing `?model=...` parameter or did you preserve backward compatibility?

Its okay if you dropped support for the old input format, I just want to be clear so I know that I need to sync up the back end changes before deploying this (post PR merge).

**Comment by NickolausDS** [comment]
Yes, I ended up rewriting all of the mesh-viewer argument parsing code so the old style is not supported with these changes.

**Comment by robes** [comment]
I think that's for the best anyway. It's looking good.

**Comment by NickolausDS** [comment]
Ok, everything should be good to go. Let me know if you see anything else.

**Comment by robes** [comment]
Excellent.

You have 2 open PRs. Are they both ready for merging?

**Comment by NickolausDS** [comment]
Yes, both #43 and #42 should also be good to go. There may be a little more to do on #42 from #38, but I think doing that in a new issue would be best.
