### ISSUE TITLE
Add labels to landmark points on mesh

### ISSUE THREAD

**Issue by BridgetDS** [informatics-isi-edu/mesh-viewer#38]
Each point should be numbered - the numbers should correspond to to labels provided in the "Meshes" and "Calculate distances" drop-downs.

There is a certain order in which we normally order the landmarks, so the user should be able to specify which number corresponds to which landmark.

**Comment by NickolausDS** [comment]
Can I double check how the ordering for landmarks is derived? For example given the list here I could see a couple different possibilities. I might suggest adding an additional optional field to each landmark called "order" to specify this feature explicitly. This make make it easier for new folks creating landmarks to understand how to order them. 
```
        "landmark": [
            {
                "group": "3V72",
                "description": null,
                "point": [9, 3, 3],
                "color": [1, 0, 0],
                "label": "2",
                "link": null,
                "radius": 0.1,
                "id": "1-3X62"
            },
            {
                "group": "3V72",
                "description": null,
                "point": [7, 2, 2],
                "color": [1, 0, 0],
                "label": "3",
                "link": null,
                "radius": 0.1,
                "id": "1-3X64"
            },
            {
                "group": "3V72",
                "description": null,
                "point": [8, 2, 3],
                "color": [1, 0, 0],
                "label": "4",
                "link": null,
                "radius": 0.1,
                "id": "1-3X66"
            },
            {
                "group": "3V72",
                "description": "Mandible 1",
                "point": [10, 3, 3],
                "color": [1, 0, 0],
                "label": "Mandible 1",
                "link": null,
                "radius": 0.1,
                "id": "1-3X60"
            }
        ],
```

**Comment by BridgetDS** [comment]
Adding an order field would be good -- our lab has [published a paper that establishes certain mouse landmarks](https://www.ncbi.nlm.nih.gov/pubmed/25722190) so we like to use that ordering for the sake of consistency, but we probably don't want to impose that on other people, and for other species/body parts there is no established order. Ideally the user would [drag-and-drop the landmarks](https://www.ncbi.nlm.nih.gov/pubmed/25722190) into the desired order.

**Comment by NickolausDS** [comment]
How about using the `order` field if it exists, but defaulting to the order they're listed in the mesh?

**Comment by BridgetDS** [comment]
Great. Thank you

**Comment by NickolausDS** [comment]
Changes are up, and handle explicit ordering, no ordering, or mixed. 

When each landmark is given a specific number, they are displayed in order from first to last like this:
<img width="374" alt="screen shot 2018-11-14 at 8 42 37 am" src="https://user-images.githubusercontent.com/865553/48499564-905bc980-e7ed-11e8-9fe9-984fd051d7dc.png">

No ordering looks like this (defaulting to the listing in the mesh):
<img width="372" alt="screen shot 2018-11-14 at 8 45 28 am" src="https://user-images.githubusercontent.com/865553/48499606-ac5f6b00-e7ed-11e8-8e23-a4813324692b.png">

And Mixed ordering looks like this, where unlisted are pushed to last:
<img width="384" alt="screen shot 2018-11-14 at 8 44 23 am" src="https://user-images.githubusercontent.com/865553/48499617-b5e8d300-e7ed-11e8-9d57-409612904b22.png">

**Comment by BridgetDS** [comment]
Great - thank you. And are the points themselves correspondingly numbered on the mesh? The goal would be something like this
<img width="1187" alt="screen shot 2018-11-14 at 9 32 21 am" src="https://user-images.githubusercontent.com/14893197/48500700-4cb68f00-e7f0-11e8-8bfe-15ef9ee5c4f9.png">

**Comment by NickolausDS** [comment]
No, can you link the location of that viewer? I can look into displaying the number alongside the landmark point on the mesh.

**Comment by BridgetDS** [comment]
http://chailab.usc.edu/3Dmodel/C57BL6-E185.html

**Comment by NickolausDS** [comment]
I looked into this one, and putting numbers on each landmark appears more daunting than expected at first glance.

Looking at the USC example above, they wrote the whole viewer in pure WebGL. The approach is to take the [image here](http://chailab.usc.edu/3Dmodel/data/digit.png) containing all the numbers and snip them into individual images so each number can be displayed independently. It does this with the `initTexture()` [function here](http://chailab.usc.edu/3Dmodel/javascript/webgl-base.js) and is fairly complex. 

Other libraries similar to XTK simplify the texture coordinate mapping. Three.js has a [built-in class](https://threejs.org/docs/#api/en/geometries/TextGeometry) for rendering text in the viewer, and additional built in utilities for [rendering sprite-sheets requiring texture coordinate mapping](http://stemkoski.github.io/Three.js/Texture-Animation.html) (see page source) like the WebGL example above.

For XTK, there don't appear to be many options. The docs support [single textures](http://api.goxtk.com/texture.html) but no built-in support for either texture coordinate mapping or text-to-texture mapping. [Text objects were proposed](https://github.com/xtk/X/issues/97) (6 years ago) but it doesn't look like they made it in I don't think it would be possible to snip a spritesheet using WebGL and render it using XTK. It may be possible to save several pre-cut images and render them individually, but that could get complex very quickly, especially if we needed to display more than 9 landmarks.

**Comment by BridgetDS** [comment]
Ok, thank you. I think a viable workaround would be for authors to just specify each landmark with a different color, and then they’ll be identifiable. I’ll do this for 972 when I have some time.

**Comment by NickolausDS** [comment]
If no extra changes are required, this should be good to go. Just for reference, issue #37 shows landmarks with different colors.

**Comment by NickolausDS** [comment]
This should now be complete in the above merged code. Please re-open or add another issue if there is anything else.
