### ISSUE TITLE
Limit distance calculations to one mesh at a time

### ISSUE THREAD

**Issue by BridgetDS** [informatics-isi-edu/mesh-viewer#39]
The user should only be able to calculate distances within a selected mesh (i.e., bone). Later we may want to add back the functionality to calculate distances across different meshes but that would require extra preparation at the time of CT scanning to make sure the jaws are positioned in the same way each time.

**Comment by NickolausDS** [comment]
This is interesting, I think I need to understand a little more about how the meshes are laid out.The model, comprising of the various meshes, is all laid out on the same coordinate system. Given that, is the error limited to the space in between the meshes, or do each of the meshes scale independently of one another? If it's the first, then I think your fix is best. If it's the second, we'll need to change the schema to allow each mesh to define its own real-world conversion to the coordinate system in mesh-viewer. In addition for the second scenario, calculating the distance between landmarks on different meshes may not be possible if the line between both landmarks intersects one or many different meshes, each with a uniquely scaled area of the coordinate system.

**Comment by BridgetDS** [comment]
The answer is complicated; we would ideally show the soft and hard tissue as part of the same model, but I haven't been able to get that to work yet because they're from two different scans (of the same mouse, taken at the same time). I haven't tried to get to the bottom of this issue yet but it's on my list.

Anyway, that being said, within a single model (for example in this case just the meshes of the hard tissue) the problem is kind of silly: sometimes the mouse has its mouth open while the image is being taken, and sometimes it doesn't. So we don't want to allow people to measure from a point on the lower jaw to a point on the upper jaw, because that is going to be biologically meaningless to compare across mice that might have been imaged in different positions.

**Comment by NickolausDS** [comment]
Ahh, ok. In that case, doing as you said before and measuring only landmarks within their parent mesh is an easy solution that puts of the more complicated fix. Do you want to go ahead and start with that for now?

**Comment by BridgetDS** [comment]
Yeah, that's what I'd suggest.

**Comment by NickolausDS** [comment]
I took another look at this one, and realized there's a bit of an ambiguity on which mesh to calculate distances for if multiple landmarks from different meshes are selected. Take for instance this little guy:

<img width="1237" alt="screen shot 2018-11-27 at 9 03 07 am" src="https://user-images.githubusercontent.com/865553/49826608-2b3bbb00-fd3c-11e8-80b2-d4b9a781c6f1.png">

In this example, red landmarks correspond to one mesh, and blue to another. 

I see a couple of different options inclusive of one another:

* If there are more than one landmarks from multiple meshes selected, "Calculate Distances" could cycle between them, changing the name of "Calculate distance on (mesh)" to the mesh it's calculating distances.
* In the 'Meshes' Menu, hiding meshes with the 'eye' button could also de-select meshes. 

Let me know your thoughts.

**Comment by BridgetDS** [comment]
I’m not exactly sure what you mean by “cycle between [meshes]” but I think both of your suggestions are good. Also, when a mesh is hidden using the eye icon, the landmarks on that mesh should be hidden as well.

**Comment by NickolausDS** [comment]
> Also, when a mesh is hidden using the eye icon, the landmarks on that mesh should be hidden as well.
Oh, interesting. Maybe that broke with the latest changes, I'll look at fixing it. 

For my first point I was thinking about how the mesh-viewer would behave when it encountered a situation like the example above, where there are two different meshes each with several landmarks selected and the user clicks the 'Calculate Distances' button. If it can only calculate landmarks for one mesh at a time, how could it do so in a way that makes sense to the user? 

At first, I was proposing a 'smart' solution where the mesh-viewer would automatically figure that out and switch between each active mesh with landmarks, but on further consideration that's going to require tracking a lot of state. 

A simpler solution would be calculating distances for the first active mesh, and hiding the others. How does that sound?

**Comment by BridgetDS** [comment]
I think that just working in the active mesh and hiding the others will be fine. Thanks

**Comment by NickolausDS** [comment]
Done and merged! Let me know if there is anything else.
