### ISSUE TITLE
Change wording in "Calculate distances" drop-down

### ISSUE THREAD

**Issue by BridgetDS** [informatics-isi-edu/mesh-viewer#40]
Instead of "Selected landmark distances" I suggest "Calculate distance from..."

Under each pin, the list should then read "[X units] to [Other Landmark]"

**Comment by NickolausDS** [comment]
This is very helpful, and is a simple fix. Thanks!

**Comment by NickolausDS** [comment]
Fix is here #41. 

A screenshot of how it looks is here (disregard the actual calculated values):

<img width="372" alt="screen shot 2018-11-08 at 9 29 54 am" src="https://user-images.githubusercontent.com/865553/48218215-3d41cc80-e33e-11e8-93c9-5ac968c30b95.png">

**Comment by BridgetDS** [comment]
Perfect. Thank you
