### ISSUE TITLE
"additional parameters" not working

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/mesh-viewer#48]
The additional parameters here seem to have stopped working.

https://github.com/informatics-isi-edu/mesh-viewer#additional-parameters

You can observe here.

https://dev.facebase.org/image-nav-demo.html

**Comment by NickolausDS** [comment]
I'll look into this one today.

**Comment by NickolausDS** [comment]
`target-url` looks like it still might work if passed as a query parameter instead of a fragment. However now that most arguments are passed as fragments, making these do the same seems like it would be better for consistency.

 Let me know if query parameters is still preferred over fragments for these two.

**Comment by robes** [comment]
Ah, that explains what happened. Still, these should all be changed to be fragment identifier parameters since they are interpreted client-side. I.e., `...#...&target-url=...&showmeshes=...`.

**Comment by NickolausDS** [comment]
One other thing, I notice `target-url` uses a dash separator while other arguments use an underscore. Do you want to change that for consistency, or leave it as-is for compatibility?

**Comment by NickolausDS** [comment]
Ok, fixes are above. Names for both params is the same, but now they're passed as fragments. I looked over the documentation, and it seemed to be previously incorrect using fragments instead of query params. Without any changes, it should now be correct and work as advertised.

**Comment by robes** [comment]
merged
